version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=user
      - MARIADB_DATABASE=app
      - MARIADB_PASSWORD=password

  myapp:
    tty: true
    image: docker.io/bitnami/laravel:8
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=user
      - DB_DATABASE=app
      - DB_PASSWORD=password
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ../../:/app
